services:
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - shakederoy_database:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"
    networks:
      - shakederoy_backend

volumes:
  shakederoy_database:

networks:
  shakederoy_backend:
    external: true
