include:
  - path: deps.docker-compose.yaml

services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    env_file: ./apps/server/.env
    ports:
      - 3000:3000
    networks:
      - shakederoy_backend
