include:
  - path: deps.docker-compose.yaml

services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    environment:
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      COOKIE_SECRET: ${COOKIE_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      NODE_ENV: ${NODE_ENV}
      APP_PORT: ${APP_PORT}
      PAGE_SIZE: ${PAGE_SIZE}
    networks:
      - shakederoy_backend
