services:
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    networks:
      - dokploy-network
    environment:
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      COOKIE_SECRET: ${COOKIE_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      NODE_ENV: ${NODE_ENV}
      APP_PORT: ${APP_PORT}
      PAGE_SIZE: ${PAGE_SIZE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

networks:
  dokploy-network:
    external: true
