name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t martni/shakederoy:latest -f ./apps/server/Dockerfile .

      - name: Push Docker image
        run: docker push martni/shakederoy:latest
        
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: deploy backend
        env:
          DEPLOYMENT_HOST: ${{ secrets.DEPLOYMENT_HOST }}
          COMPOSE_ID: ${{ secrets.COMPOSE_ID }}
        run: "curl -X POST $DEPLOYMENT_HOST/compose.redeploy -H \"Content-Type: application/json\" -d '{\"composeId\":\"'\"$COMPOSE_ID\"'\",\"title\":\"osef\",\"description\":\"osef\"}'"
