name: Deploy Backend - Staging

on:
  push:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t martni/shakederoy:staging -f ./apps/server/Dockerfile .

      - name: Push Docker image
        run: docker push martni/shakederoy:staging
        
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy backend
        env:
          DEPLOYMENT_HOST: ${{ secrets.DEPLOYMENT_HOST }}
          COMPOSE_ID: ${{ secrets.COMPOSE_ID }}
          API_KEY: ${{ secrets.DEPLOYMENT_API_KEY }}
        run: "curl -X POST $DEPLOYMENT_HOST/api/compose.redeploy -H \"Content-Type: application/json\" -H \"x-api-key: $API_KEY\" -d '{\"composeId\":\"'\"$COMPOSE_ID\"'\"}'"
