name: Deploy Backend

on:
  push:
    branches: [staging, main]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-env.outputs.tag }}
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: Set environment variables
        id: set-env
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
            echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "tag=staging" >> $GITHUB_OUTPUT
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t martni/shakederoy:${{ steps.set-env.outputs.tag }} -f ./apps/server/Dockerfile .

      - name: Push Docker image
        run: docker push martni/shakederoy:${{ steps.set-env.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ needs.build.outputs.environment }}
    steps:
      - name: Deploy backend
        env:
          DEPLOYMENT_HOST: ${{ secrets.DEPLOYMENT_HOST }}
          COMPOSE_ID: ${{ secrets.COMPOSE_ID }}
          API_KEY: ${{ secrets.DEPLOYMENT_API_KEY }}
        run: |
          curl -X POST $DEPLOYMENT_HOST/api/compose.redeploy \
            -H "Content-Type: application/json" \
            -H "x-api-key: $API_KEY" \
            -d '{"composeId":"'"$COMPOSE_ID"'"}'
